demosite = "https://willfaught.com/paige"
description = "Powerful, pliable pixel perfection. An advanced Hugo theme."
features = [
  "accessibility",
  "atom feeds",
  "authors",
  "blog",
  "bootstrap styles and icons",
  "breadcrumbs",
  "categories",
  "code shortcode",
  "customizable",
  "dark color scheme",
  "email shortcode",
  "facebook sharing",
  "figure shortcode",
  "gallery shortcode",
  "icon shortcode",
  "image pixel densities",
  "image shortcode",
  "image size breakpoints",
  "image thumbnails",
  "internationalization",
  "landing page",
  "light color scheme",
  "localizations",
  "math typesetting",
  "menu",
  "minimal design",
  "quote shortcode",
  "responsive",
  "right-to-left languages",
  "rss feeds",
  "safari and firefox reader view support",
  "search",
  "sections",
  "seo",
  "series",
  "single column",
  "tab shortcode",
  "table of contents",
  "tags",
  "title links",
  "twitter sharing",
  "validated",
  "vimeo shortcode",
  "youtube shortcode",
]
homepage = "https://github.com/willfaught/paige"
license = "MIT"
licenselink = "https://github.com/willfaught/paige/blob/master/LICENSE"
name = "Paige"
tags = [
  "archive",
  "blog",
  "bootstrap",
  "company",
  "contact",
  "dark mode",
  "dark",
  "docs",
  "gallery",
  "hero",
  "landing",
  "light",
  "minimal",
  "multilingual",
  "personal",
  "podcast",
  "portfolio",
  "responsive",
]

[author]
homepage = "https://willfaught.com"
name = "Will Faught"
